name: Build DOSmax Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile DOSmax.py

    - name: Upload .exe to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/DOSmax.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
